name: Run T-SQL via GitHub Actions

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  run-tsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SQL Server tools
        uses: microsoft/setup-msbuild@v1
        with:
          dotnet-version: 'latest'  # Change this if necessary

      - name: Run T-SQL script
        run: |
          sqlcmd
          # Run your T-SQL commands here
          # Example:
          # sqlcmd -S <server_name> -d <database_name> -U <username> -P <password> -i path/to/script.sql
          # Make sure to set up appropriate secrets or credentials for secure access
          

