name: Run T-SQL via GitHub Actions

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  run-tsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: List T-SQL Scripts
        id: list-scripts
        run: |
          script_paths=$(find . -type f -name '*.sql')
          scripts=""
          for path in $script_paths; do
            scripts="$scripts$path"
          done
          echo "::set-output name=scripts::$scripts"          
    



      - name: Install SQL Server tools
        run: |
          # Import the Microsoft repository GPG keys
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

          # Register the Microsoft SQL Server repository
          sudo add-apt-repository "$(curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list)"

          # Update the package list
          sudo apt-get update

          # Install SQL Server tools
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

          # Add sqlcmd to the PATH
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run T-SQL script
        run: |
          for sqlfile in ${{ steps.list-scripts.outputs.scripts }} ; do
            echo "sqlcmd $sqlfile"
          done
