name:  Mendax Example

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest

    steps:
      - name: Mendax Loop through numbers
        id: loop
        run: |
          for file in ( TestingTSQL.yml test )
          do
            echo "$file"
          done
