REPO="owner/repo"
ARTIFACT_NAME="my-artifact"

# Get the list of artifacts and filter by name to get the download URL
DOWNLOAD_URL=$(gh api -H "Accept: application/vnd.github.v3+json" /repos/$REPO/actions/artifacts | jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .archive_download_url")

if [ -n "$DOWNLOAD_URL" ]; then
  # Download the artifact using curl
  curl -L -H "Authorization: token $GITHUB_TOKEN" -o artifact.zip $DOWNLOAD_URL
  echo "Artifact downloaded successfully: artifact.zip"
else
  echo "Artifact with name $ARTIFACT_NAME not found."
fi
