---
name: manifests

on: [push, pull_request]

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')"




  apply-sql:
    needs: list-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.list-files.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Apply sql files
        run: |-
          echo ${{ matrix.manifest }} 
