name: manifests
on:
  push:
    branches:
      - main 
job1:
  runs-on: ubuntu-latest
  outputs:
    matrix: ${{ steps.set-matrix.outputs.matrix }}
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - id: set-matrix
      run: echo "::set-output name=matrix::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
job2:
  name: ${{ matrix.stack }}
  needs: job1
  runs-on: ubuntu-latest
  strategy:
    matrix:
      stack: ${{fromJSON(needs.job1.outputs.matrix)}}
