name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:   
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2    
      - id: set-matrix
        run: |
          script_paths=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} )
          echo "::set-output name=matrix::{\"node\":[ "script_paths" ]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: echo "test"
