name: iterate

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  run-tsql:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list-scripts.outputs.scripts }}    
#    strategy:
#      matrix:
#        version: ${{ github.event.client_payload.versions }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: List T-SQL Scripts
        id: list-scripts
        run: |
          script_paths=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} )
          echo $script_paths
          scripts=""
          for path in $script_paths; do
            scripts="$scripts $path"
          done
          echo "::set-output name=scripts::$scripts"   

          
          
