name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' #    
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x  # Adjust version as needed

    - name: Cache SonarQube Scanner
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: sonarqube-${{ runner.os }}-${{ hashFiles('*/.csproj') }}
        restore-keys: |
          sonarqube-${{ runner.os }}-

    - name: SonarQube Scan
      run: |
        dotnet tool install --global dotnet-sonarscanner --version 6.0.0
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet sonarscanner begin /k:"kanchan2008_codecoverage" /o:"kanchan2008" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        dotnet restore SampleApp/SampleApp.csproj
        dotnet build SampleApp/SampleApp.csproj
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Upload SonarQube Quality Gate Status
      uses: SonarSource/sonarcloud-github-action@master
      with: 
        projectBaseDir:  ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        waitForQualityGate: true
        
