name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - qa
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Kubeconfig
      run: |
        if [ "${{ github.event.inputs.environment }}" == "development" ]; then
          echo "${{ secrets.KUBE_CONFIG_DEV }}" > ~/.kube/config
        elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
          echo "${{ secrets.KUBE_CONFIG_QA }}" > ~/.kube/config
        elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
          echo "${{ secrets.KUBE_CONFIG_PROD }}" > ~/.kube/config
        fi

    - name: Deploy to Kubernetes
      run: |
        if [ "${{ github.event.inputs.environment }}" == "development" ]; then
          kubectl apply -f deployment-dev.yaml
        elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
          kubectl apply -f deployment-qa.yaml
        elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
          kubectl apply -f deployment-prod.yaml
        fi
