name: Build and Tag Docker Image

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract and sanitize branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF##*/}
          SANITIZED_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/^v//')
          echo "::set-output name=sanitized_branch_name::$SANITIZED_BRANCH_NAME"

      - name: Build Docker image
        run: docker build -t myapp:${{ steps.extract_branch.outputs.sanitized_branch_name }}-${{ github.event.number }} .

      - name: Push Docker image
        run: docker push myapp:${{ steps.extract_branch.outputs.sanitized_branch_name }}-${{ github.event.number }}
