name: Trigger Action from Docker Images
   
on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Select Docker Image'
        required: true
        options: ${{ steps.get_images.outputs.available_images }}

jobs:
  get_images:
    runs-on: ubuntu-latest
    outputs:
      available_images: ${{ steps.set_available_images.outputs.available_images }}
    steps:
      - name: Retrieve Available Docker Images
        id: set_available_images
        run: |
          # Use your script or command to retrieve the list of images
          # Store the list in a file or output it as JSON
          # For demonstration, setting a static list here
          echo "::set-output name=available_images::['image1', 'image2', 'image3']"
